version: '3.4'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: net_test_case.postgres
    environment:
      - POSTGRES_BD=net_test_case
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5433:5432